services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5000}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=${BACKEND_URL}/api
    ports:
      - "80:80"
    depends_on:
      - backend