version: '3.8'

services:
  backend:
    build: ./backend
    container_name: portfolio-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    restart: unless-stopped

networks:
  default:
    name: portfolio-network